// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ubidding_config.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/UbiXGPBProtocolBuffers.h>
#else
 #import <UbiXDaq/UbiXGPBProtocolBuffers_RuntimeSupport.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UBiddingBaseABTest;
@class UBiddingPbBaseAdnConfig;
@class UBiddingPbBaseConfigResponse;
@class UBiddingPbBaseSlotConfig;
@class UBiddingPbRequest_UADXPbMDSlot;
@class UBiddingPbRequest_UBiddingADNInfo;
@class UBiddingPbRequest_UBiddingPbAppInfo;
@class UBiddingPbRequest_UBiddingPbDeviceInfo;
@class UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId;
@class UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbGeo;
@class UBiddingPbRequest_UBiddingPbMDSlot;
@class UBiddingPbRequest_UBiddingPbUserInfo;
@class UBiddingPbResponse_UADXPbConfigResponse;
@class UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig;
@class UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_UADXPbAdnConfig;
@class UBiddingPbResponse_UADXPbMaterialModule;
@class UBiddingPbResponse_UBiddingPbAdnAppInfo;
@class UBiddingPbResponse_UBiddingPbAdnInfo;
@class UBiddingPbResponse_UBiddingPbConfigResponse;
@class UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig;
@class UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdCache;
@class UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdnConfig;
@class UBiddingPbResponse_UBiddingPbInitResponse;
@class UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule;
@class UBiddingPbResponse_UBiddingPbMaterialModule;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UbiddingConfigRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (UbiXGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c UbiXGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
UbiX_GPB_FINAL @interface UbiddingConfigRoot : UbiXGPBRootObject
@end

#pragma mark - UBiddingPbRequest

typedef UbiX_GPB_ENUM(UBiddingPbRequest_FieldNumber) {
  UBiddingPbRequest_FieldNumber_UbiddingpbSdkVersion = 1,
  UBiddingPbRequest_FieldNumber_UbiddingpbTimestamp = 2,
  UBiddingPbRequest_FieldNumber_UbiddingpbRequestId = 3,
  UBiddingPbRequest_FieldNumber_UbiddingpbConfigType = 4,
  UBiddingPbRequest_FieldNumber_UbiddingpbApp = 5,
  UBiddingPbRequest_FieldNumber_UbiddingpbDevice = 6,
  UBiddingPbRequest_FieldNumber_UbiddingpbUserInfo = 7,
  UBiddingPbRequest_FieldNumber_UbiddingpbMdSlotArray = 8,
  UBiddingPbRequest_FieldNumber_UbiddingpbAdnInfoArray = 9,
  UBiddingPbRequest_FieldNumber_UbiddingpbKsVersion = 10,
  UBiddingPbRequest_FieldNumber_UbiddingpbInitResponseMd5 = 11,
};

UbiX_GPB_FINAL @interface UBiddingPbRequest : UbiXGPBMessage

/** 必填。当前sdk的版本。格式如：1.0.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbSdkVersion;

/** 触发时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbTimestamp;

/** 初始化或请求策略的requestID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbRequestId;

/** 1:全量下发配置， 2:下发单个广告位（不下发云控配置） */
@property(nonatomic, readwrite) int32_t ubiddingpbConfigType;

/** 必填。移动app的信息。 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbRequest_UBiddingPbAppInfo *ubiddingpbApp;
/** Test to see if @c ubiddingpbApp has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbApp;

/** 必填。移动设备的信息。 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbRequest_UBiddingPbDeviceInfo *ubiddingpbDevice;
/** Test to see if @c ubiddingpbDevice has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbDevice;

/** 用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbRequest_UBiddingPbUserInfo *ubiddingpbUserInfo;
/** Test to see if @c ubiddingpbUserInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbUserInfo;

/** 聚合广告位 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbRequest_UBiddingPbMDSlot*> *ubiddingpbMdSlotArray;
/** The number of items in @c ubiddingpbMdSlotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbMdSlotArray_Count;

/** 端上固定上报源信息，4.0.0仅用于md5复用 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbRequest_UBiddingADNInfo*> *ubiddingpbAdnInfoArray;
/** The number of items in @c ubiddingpbAdnInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbAdnInfoArray_Count;

/** 快手共存不生效版本sdk的版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbKsVersion;

/** 初始化信息 md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbInitResponseMd5;

@end

#pragma mark - UBiddingPbRequest_UBiddingADNInfo

typedef UbiX_GPB_ENUM(UBiddingPbRequest_UBiddingADNInfo_FieldNumber) {
  UBiddingPbRequest_UBiddingADNInfo_FieldNumber_UbiddingpbAdnId = 1,
  UBiddingPbRequest_UBiddingADNInfo_FieldNumber_UbiddingpbAdnResponseMd5 = 2,
};

/**
 * 广告网络信息
 **/
UbiX_GPB_FINAL @interface UBiddingPbRequest_UBiddingADNInfo : UbiXGPBMessage

/** 聚合ADN id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAdnId;

/** response md5 是否刷新广告平台信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAdnResponseMd5;

@end

#pragma mark - UBiddingPbRequest_UBiddingPbMDSlot

typedef UbiX_GPB_ENUM(UBiddingPbRequest_UBiddingPbMDSlot_FieldNumber) {
  UBiddingPbRequest_UBiddingPbMDSlot_FieldNumber_UbiddingpbSlotId = 1,
  UBiddingPbRequest_UBiddingPbMDSlot_FieldNumber_UbiddingpbAdType = 2,
  UBiddingPbRequest_UBiddingPbMDSlot_FieldNumber_UbiddingpbTrafficGroupMd5 = 3,
  UBiddingPbRequest_UBiddingPbMDSlot_FieldNumber_UbiddingpbMdSlotArray = 4,
};

UbiX_GPB_FINAL @interface UBiddingPbRequest_UBiddingPbMDSlot : UbiXGPBMessage

/** 聚合广告位id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbSlotId;

/** 请求的广告类型: 1开屏，2信息流，3激励视频，4横幅，5插屏，6全屏视频，7贴片 */
@property(nonatomic, readwrite) int32_t ubiddingpbAdType;

/** Saas流量组的md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbTrafficGroupMd5;

/** UADX广告位 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbRequest_UADXPbMDSlot*> *ubiddingpbMdSlotArray;
/** The number of items in @c ubiddingpbMdSlotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbMdSlotArray_Count;

@end

#pragma mark - UBiddingPbRequest_UADXPbMDSlot

typedef UbiX_GPB_ENUM(UBiddingPbRequest_UADXPbMDSlot_FieldNumber) {
  UBiddingPbRequest_UADXPbMDSlot_FieldNumber_UbiddingpbSlotId = 1,
  UBiddingPbRequest_UADXPbMDSlot_FieldNumber_UbiddingpbTrafficGroupMd5 = 2,
};

UbiX_GPB_FINAL @interface UBiddingPbRequest_UADXPbMDSlot : UbiXGPBMessage

/** UADX广告位id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbSlotId;

/** UADX流量组的md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbTrafficGroupMd5;

@end

#pragma mark - UBiddingPbRequest_UBiddingPbUserInfo

typedef UbiX_GPB_ENUM(UBiddingPbRequest_UBiddingPbUserInfo_FieldNumber) {
  UBiddingPbRequest_UBiddingPbUserInfo_FieldNumber_UbiddingpbUid = 1,
  UBiddingPbRequest_UBiddingPbUserInfo_FieldNumber_UbiddingpbChannel = 2,
  UBiddingPbRequest_UBiddingPbUserInfo_FieldNumber_UbiddingpbSubChannel = 3,
  UBiddingPbRequest_UBiddingPbUserInfo_FieldNumber_UbiddingpbIsSubscriber = 4,
  UBiddingPbRequest_UBiddingPbUserInfo_FieldNumber_UbiddingpbPubSegmentId = 5,
};

/**
 * 用户信息。
 **/
UbiX_GPB_FINAL @interface UBiddingPbRequest_UBiddingPbUserInfo : UbiXGPBMessage

/** 用户在媒体上注册的ID。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbUid;

/** 渠道，由开发者自定义 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbChannel;

/** 子渠道，由开发者自定义 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbSubChannel;

/** 付费用户。0: 未知；1: 否；2: 是 */
@property(nonatomic, readwrite) int32_t ubiddingpbIsSubscriber;

/** 开发者的流量分组ID或者标签ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbPubSegmentId;

@end

#pragma mark - UBiddingPbRequest_UBiddingPbAppInfo

typedef UbiX_GPB_ENUM(UBiddingPbRequest_UBiddingPbAppInfo_FieldNumber) {
  UBiddingPbRequest_UBiddingPbAppInfo_FieldNumber_UbiddingpbAppId = 1,
  UBiddingPbRequest_UBiddingPbAppInfo_FieldNumber_UbiddingpbPackageName = 2,
  UBiddingPbRequest_UBiddingPbAppInfo_FieldNumber_UbiddingpbVersion = 3,
  UBiddingPbRequest_UBiddingPbAppInfo_FieldNumber_UbiddingpbInstallTime = 4,
};

UbiX_GPB_FINAL @interface UBiddingPbRequest_UBiddingPbAppInfo : UbiXGPBMessage

/** 必填。媒体的应用ID。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAppId;

/** 必填。IOS填写bundleID，Android填写包名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbPackageName;

/** 必填。 app的版本信息。格式如：1.0.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbVersion;

/** 安装时间，unix时间戳，单位毫秒 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbInstallTime;

@end

#pragma mark - UBiddingPbRequest_UBiddingPbDeviceInfo

typedef UbiX_GPB_ENUM(UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber) {
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbDid = 1,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbDeviceType = 2,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbOsType = 3,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbOsVersion = 4,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbVendor = 5,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbModel = 6,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbHwModel = 7,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbHwMachine = 8,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbLanguage = 9,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbConnType = 10,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbScreenWidth = 11,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbScreenHeight = 12,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbDpi = 13,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbDeviceName = 14,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbOrientation = 15,
  UBiddingPbRequest_UBiddingPbDeviceInfo_FieldNumber_UbiddingpbGeo = 16,
};

UbiX_GPB_FINAL @interface UBiddingPbRequest_UBiddingPbDeviceInfo : UbiXGPBMessage

/** 设备ID信息。必填 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId *ubiddingpbDid;
/** Test to see if @c ubiddingpbDid has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbDid;

/** 必填。设备类型。0: Unknown, 1: Phone, 2: Tablet */
@property(nonatomic, readwrite) int32_t ubiddingpbDeviceType;

/** 必填。操作系统类型。0: Unknown, 1: Android, 2: IOS */
@property(nonatomic, readwrite) int32_t ubiddingpbOsType;

/** 可选。操作系统版本。格式如：1.0.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbOsVersion;

/** 必填。设备厂商，如Apple, Samsung */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbVendor;

/** Android必填。设备机型名称，如：iPhone 11 Pro, Galaxy */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbModel;

/** IOS必填。IOS系统型号。比如：iPhone12,1 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbHwModel;

/** IOS必填 cpu型号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbHwMachine;

/** 可选。设备设置的语言 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbLanguage;

/** 可选。设备的网络类型。0: Unknown, 1: Wifi, 2: 2G, 3: 3G, 4: 4G 5：5G */
@property(nonatomic, readwrite) int32_t ubiddingpbConnType;

/** 屏幕宽度。单位：像素 */
@property(nonatomic, readwrite) uint32_t ubiddingpbScreenWidth;

/** 屏幕高度。单位：像素 */
@property(nonatomic, readwrite) uint32_t ubiddingpbScreenHeight;

/** 建议。屏幕密度 */
@property(nonatomic, readwrite) float ubiddingpbDpi;

/** 建议。手机名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbDeviceName;

/** 建议。设备屏幕方向。0: Unknown, 1: 竖屏, 2: 横屏 */
@property(nonatomic, readwrite) int32_t ubiddingpbOrientation;

/** 地理位置 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbGeo *ubiddingpbGeo;
/** Test to see if @c ubiddingpbGeo has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbGeo;

@end

#pragma mark - UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbGeo

typedef UbiX_GPB_ENUM(UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbGeo_FieldNumber) {
  UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbGeo_FieldNumber_UbiddingpbLatitude = 1,
  UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbGeo_FieldNumber_UbiddingpbLongitude = 2,
};

UbiX_GPB_FINAL @interface UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbGeo : UbiXGPBMessage

/** 推荐。GPS纬度，开发者传入 */
@property(nonatomic, readwrite) double ubiddingpbLatitude;

/** 推荐。GPS经度，开发者传入 */
@property(nonatomic, readwrite) double ubiddingpbLongitude;

@end

#pragma mark - UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId

typedef UbiX_GPB_ENUM(UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId_FieldNumber) {
  UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId_FieldNumber_UbiddingpbIdfa = 1,
  UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId_FieldNumber_UbiddingpbIdfv = 2,
  UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId_FieldNumber_UbiddingpbImei = 3,
  UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId_FieldNumber_UbiddingpbOaid = 4,
  UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId_FieldNumber_UbiddingpbAid = 5,
  UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId_FieldNumber_UbiddingpbClientId = 6,
};

/**
 * 设备ID类信息
 **/
UbiX_GPB_FINAL @interface UBiddingPbRequest_UBiddingPbDeviceInfo_UBiddingPbDeviceId : UbiXGPBMessage

/** iOS必填。IOS为IDFA（明文，大写），带"-"，若取不到则传空值"" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbIdfa;

/** iOS必填，若取不到则传空值"" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbIdfv;

/** Android必填 设备IMEI（明文），Android必填，若取不到则传空值"". */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbImei;

/** Android必填 匿名设备标识符，原文 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbOaid;

/** Android必填 原文，明文 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAid;

/** 端上client id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbClientId;

@end

#pragma mark - UBiddingPbResponse

typedef UbiX_GPB_ENUM(UBiddingPbResponse_FieldNumber) {
  UBiddingPbResponse_FieldNumber_InitResponse = 1,
  UBiddingPbResponse_FieldNumber_ConfigResponse = 2,
  UBiddingPbResponse_FieldNumber_UadxConfigResponse = 3,
  UBiddingPbResponse_FieldNumber_UbiddingpbAdnInfo = 4,
  UBiddingPbResponse_FieldNumber_UbiddingpbAdnAppInfo = 5,
  UBiddingPbResponse_FieldNumber_UbiddingpbClientIp = 6,
  UBiddingPbResponse_FieldNumber_UbiddingpbTimestamp = 7,
};

UbiX_GPB_FINAL @interface UBiddingPbResponse : UbiXGPBMessage

/** 云控配置 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbResponse_UBiddingPbInitResponse *initResponse;
/** Test to see if @c initResponse has been set. */
@property(nonatomic, readwrite) BOOL hasInitResponse;
- (UBiddingPbResponse_UBiddingPbInitResponse *)initResponse UbiX_GPB_METHOD_FAMILY_NONE;

/** Saas广告策略 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbResponse_UBiddingPbConfigResponse *configResponse;
/** Test to see if @c configResponse has been set. */
@property(nonatomic, readwrite) BOOL hasConfigResponse;

/** UADX广告策略 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbResponse_UADXPbConfigResponse *uadxConfigResponse;
/** Test to see if @c uadxConfigResponse has been set. */
@property(nonatomic, readwrite) BOOL hasUadxConfigResponse;

/** 广告平台信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, UBiddingPbResponse_UBiddingPbAdnInfo*> *ubiddingpbAdnInfo;
/** The number of items in @c ubiddingpbAdnInfo without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbAdnInfo_Count;

/** 广告平台关系信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, UBiddingPbResponse_UBiddingPbAdnAppInfo*> *ubiddingpbAdnAppInfo;
/** The number of items in @c ubiddingpbAdnAppInfo without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbAdnAppInfo_Count;

/** 客户端发起请求时的公网IP（由服务端解析） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbClientIp;

/** 时间戳 */
@property(nonatomic, readwrite) int64_t ubiddingpbTimestamp;

@end

#pragma mark - UBiddingPbResponse_UBiddingPbInitResponse

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber) {
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbStatusCode = 1,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbCollectModule = 2,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbBackupDomain = 3,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbMaterialBackupDomain = 4,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbConfigRequestInterval = 5,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbExt = 6,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbAdnDADDisable = 7,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbResponseMd5 = 8,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbConfigChanged = 9,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbMaterialModule = 10,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UadxMaterialModule = 11,
  UBiddingPbResponse_UBiddingPbInitResponse_FieldNumber_UbiddingpbcacheExpireTime = 12,
};

/**
 * 应用云控配置
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UBiddingPbInitResponse : UbiXGPBMessage

/** 状态码, 0:成功 非0对应不同的错误码。 */
@property(nonatomic, readwrite) int32_t ubiddingpbStatusCode;

/** 采集模块 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule *ubiddingpbCollectModule;
/** Test to see if @c ubiddingpbCollectModule has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbCollectModule;

/** 聚合服务备用域名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbBackupDomain;

/** 素材备用域名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbMaterialBackupDomain;

/** 全量配置请求时间间隔, 默认缺省值: 600 (=10分钟)， 单位:s */
@property(nonatomic, readwrite) int32_t ubiddingpbConfigRequestInterval;

/** 通用扩展字段，json格式，由客户端解析;同聚合广告代码位的高级配置。可以自定义下发拓展参数。后续如：崩溃白名单包名、传感器开关云控 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbExt;

/** adn_diff_appid_disable; false app共存生效，true app共存不生效，4.0.0仅有Ks */
@property(nonatomic, readwrite) BOOL ubiddingpbAdnDADDisable;

/** response md5,生成规则不包括 （28时间戳） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbResponseMd5;

/** 是否需要更新初始化配置 */
@property(nonatomic, readwrite) BOOL ubiddingpbConfigChanged;

/** Saas 素材黑名单缓存配置模块 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbResponse_UBiddingPbMaterialModule *ubiddingpbMaterialModule;
/** Test to see if @c ubiddingpbMaterialModule has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbMaterialModule;

/** UAdx 素材黑名单缓存配置模块 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbResponse_UADXPbMaterialModule *uadxMaterialModule;
/** Test to see if @c uadxMaterialModule has been set. */
@property(nonatomic, readwrite) BOOL hasUadxMaterialModule;

/** 缓存广告的失效时间，默认30*60秒 */
@property(nonatomic, readwrite) int32_t ubiddingpbcacheExpireTime;

@end

#pragma mark - UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber) {
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbStatus = 1,
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbBackupDomain = 2,
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbInterval = 3,
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbBatchSize = 4,
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbBlockTrackingStatusCodeArray = 5,
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbUadxBlockTrackingStatusCodeArray = 6,
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbUb = 7,
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbSm = 8,
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbPT = 9,
  UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule_FieldNumber_UbiddingpbMaterialRatio = 10,
};

/**
 * 采集模块
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UBiddingPbInitResponse_UBiddingPbCollectModule : UbiXGPBMessage

/** 状态 1 开启， 2 关闭 */
@property(nonatomic, readwrite) int32_t ubiddingpbStatus;

/** 采集服务备用域名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbBackupDomain;

/** 定时周期  单位：秒，默认15秒 */
@property(nonatomic, readwrite) int32_t ubiddingpbInterval;

/** 一次批量上报事件上限 */
@property(nonatomic, readwrite) int32_t ubiddingpbBatchSize;

/** SaaS非必要埋点范围,拦截逻辑，引擎下发埋点状态码值，sdk识别到码值则过滤该码值上报。sdk默认上报全部埋点。 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *ubiddingpbBlockTrackingStatusCodeArray;
/** The number of items in @c ubiddingpbBlockTrackingStatusCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbBlockTrackingStatusCodeArray_Count;

/** UADX非必要埋点范围,拦截逻辑，引擎下发埋点状态码值，sdk识别到码值则过滤该码值上报。sdk默认上报全部埋点。 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *ubiddingpbUadxBlockTrackingStatusCodeArray;
/** The number of items in @c ubiddingpbUadxBlockTrackingStatusCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbUadxBlockTrackingStatusCodeArray_Count;

/** 是否监测USB调试，1=不监测(默认)、2=监测、3=监测+拦截, 仅Android */
@property(nonatomic, readwrite) int32_t ubiddingpbUb;

/** 是否监测SIM卡，1=不监测(默认)、2=监测、3=监测+拦截,Android+iOS */
@property(nonatomic, readwrite) int32_t ubiddingpbSm;

/** protect_time，新安装设备拦截时间阈值，单位秒, "0"代表不设置拦截，未设值端上使用默认值3天，Android+iOS */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbPT;

/** <=0:不采集，>=100 全量采集； 其他按比例采样 */
@property(nonatomic, readwrite) int32_t ubiddingpbMaterialRatio;

@end

#pragma mark - UBiddingPbResponse_UBiddingPbMaterialModule

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UBiddingPbMaterialModule_FieldNumber) {
  UBiddingPbResponse_UBiddingPbMaterialModule_FieldNumber_UbiddingpbMaterialRules = 1,
  UBiddingPbResponse_UBiddingPbMaterialModule_FieldNumber_UbiddingpbMaterialCacheTime = 2,
  UBiddingPbResponse_UBiddingPbMaterialModule_FieldNumber_UbiddingpbMaterialCacheCount = 3,
  UBiddingPbResponse_UBiddingPbMaterialModule_FieldNumber_UbiddingpbMaterialStatus = 4,
};

/**
 * Saas 素材黑名单缓存配置模块
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UBiddingPbMaterialModule : UbiXGPBMessage

/** 是否有素材屏蔽规则。1:有 2:没有 */
@property(nonatomic, readwrite) int32_t ubiddingpbMaterialRules;

/** 黑名单素材缓存时间。单位：秒，默认 7*24*60秒 */
@property(nonatomic, readwrite) int32_t ubiddingpbMaterialCacheTime;

/** 素材库缓存条数 默认1000条。 */
@property(nonatomic, readwrite) int32_t ubiddingpbMaterialCacheCount;

/** 素材过滤开关 1 开启， 2 关闭 */
@property(nonatomic, readwrite) int32_t ubiddingpbMaterialStatus;

@end

#pragma mark - UBiddingPbResponse_UADXPbMaterialModule

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UADXPbMaterialModule_FieldNumber) {
  UBiddingPbResponse_UADXPbMaterialModule_FieldNumber_UbiddingpbMaterialRules = 1,
  UBiddingPbResponse_UADXPbMaterialModule_FieldNumber_UbiddingpbMaterialCacheTime = 2,
  UBiddingPbResponse_UADXPbMaterialModule_FieldNumber_UbiddingpbMaterialCacheCount = 3,
  UBiddingPbResponse_UADXPbMaterialModule_FieldNumber_UbiddingpbMaterialStatus = 4,
};

/**
 * UAdx 素材黑名单缓存配置模块
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UADXPbMaterialModule : UbiXGPBMessage

/** 是否有素材屏蔽规则。1:有 2:没有 */
@property(nonatomic, readwrite) int32_t ubiddingpbMaterialRules;

/** 黑名单素材缓存时间。单位：秒，默认 7*24*60秒 */
@property(nonatomic, readwrite) int32_t ubiddingpbMaterialCacheTime;

/** 素材库缓存条数 默认1000条。 */
@property(nonatomic, readwrite) int32_t ubiddingpbMaterialCacheCount;

/** 素材过滤开关 1 开启， 2 关闭 */
@property(nonatomic, readwrite) int32_t ubiddingpbMaterialStatus;

@end

#pragma mark - UBiddingPbResponse_UBiddingPbAdnInfo

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber) {
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbAdnId = 1,
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbCustomType = 2,
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbInitAdapterClassName = 3,
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbSplashAdapterClassName = 4,
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbNativeAdapterClassName = 5,
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbInterstitialAdapterClassName = 6,
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbRewardAdapterClassName = 7,
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbBannerAdapterClassName = 8,
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbResponseMd5 = 9,
  UBiddingPbResponse_UBiddingPbAdnInfo_FieldNumber_UbiddingpbConfigChanged = 10,
};

/**
 * 广告平台信息
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UBiddingPbAdnInfo : UbiXGPBMessage

/** 平台枚举值 */
@property(nonatomic, readwrite) int64_t ubiddingpbAdnId;

/** 1:默认接入，2:自定义广告平台接入 */
@property(nonatomic, readwrite) int32_t ubiddingpbCustomType;

/** 初始化， Android adapter包名 / iOS adapter类名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbInitAdapterClassName;

/** 开屏， Android adapter包名 / iOS adapter类名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbSplashAdapterClassName;

/** 信息流， Android adapter包名 / iOS adapter类名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbNativeAdapterClassName;

/** 插屏， Android adapter包名 / iOS adapter类名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbInterstitialAdapterClassName;

/** 激励， Android adapter包名 / iOS adapter类名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbRewardAdapterClassName;

/** 横幅， Android adapter包名 / iOS adapter类名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbBannerAdapterClassName;

/** response md5,生成规则不包括 （28时间戳） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbResponseMd5;

/** 是否需要更新广告平台信息 */
@property(nonatomic, readwrite) BOOL ubiddingpbConfigChanged;

@end

#pragma mark - UBiddingPbResponse_UBiddingPbAdnAppInfo

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber) {
  UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber_UbiddingpbAdnId = 1,
  UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber_UbiddingpbAdnName = 2,
  UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber_UbiddingpbAppAdnId = 3,
  UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber_UbiddingpbAdnAppId = 4,
  UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber_UbiddingpbAdnAppName = 5,
  UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber_UbiddingpbAdnAppKey = 6,
  UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber_UbiddingpbAdnAccount = 7,
  UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber_UbiddingpbInitAdapterParams = 8,
  UBiddingPbResponse_UBiddingPbAdnAppInfo_FieldNumber_UbiddingpbAdnAccountInnerId = 9,
};

/**
 * 广告平台关系信息
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UBiddingPbAdnAppInfo : UbiXGPBMessage

/** 平台枚举值 */
@property(nonatomic, readwrite) int64_t ubiddingpbAdnId;

/** 广告网络名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAdnName;

/** app 广告源关系 id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAppAdnId;

/** 广告源app id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAdnAppId;

/** 广告源app name */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAdnAppName;

/** 广告源app key */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAdnAppKey;

/** 外部广告账户 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAdnAccount;

/** 初始化，扩展参数。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbInitAdapterParams;

/** 广告账户资产ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAdnAccountInnerId;

@end

#pragma mark - UBiddingPbResponse_UBiddingPbConfigResponse

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UBiddingPbConfigResponse_FieldNumber) {
  UBiddingPbResponse_UBiddingPbConfigResponse_FieldNumber_UbiddingpbBaseConfigs = 1,
  UBiddingPbResponse_UBiddingPbConfigResponse_FieldNumber_UbiddingpbSlotConfigsArray = 2,
};

/**
 * Saas 广告策略
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UBiddingPbConfigResponse : UbiXGPBMessage

/** 公共结构 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseConfigResponse *ubiddingpbBaseConfigs;
/** Test to see if @c ubiddingpbBaseConfigs has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbBaseConfigs;

/** 策略模块 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig*> *ubiddingpbSlotConfigsArray;
/** The number of items in @c ubiddingpbSlotConfigsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbSlotConfigsArray_Count;

@end

#pragma mark - UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_FieldNumber) {
  UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_FieldNumber_UbiddingpbBaseSlotConfig = 1,
  UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_FieldNumber_UbiddingpbAdSourcesArray = 2,
  UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_FieldNumber_UbiddingpbAdCache = 3,
  UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_FieldNumber_UbiddingpbAbTest = 4,
};

/**
 * Saas 流量组策略
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig : UbiXGPBMessage

/** 公共结构 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseSlotConfig *ubiddingpbBaseSlotConfig;
/** Test to see if @c ubiddingpbBaseSlotConfig has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbBaseSlotConfig;

/** 广告源列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdnConfig*> *ubiddingpbAdSourcesArray;
/** The number of items in @c ubiddingpbAdSourcesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbAdSourcesArray_Count;

/** 广告缓存设置参数 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdCache *ubiddingpbAdCache;
/** Test to see if @c ubiddingpbAdCache has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbAdCache;

/** ABTest */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingBaseABTest *ubiddingpbAbTest;
/** Test to see if @c ubiddingpbAbTest has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbAbTest;

@end

#pragma mark - UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdnConfig

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdnConfig_FieldNumber) {
  UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdnConfig_FieldNumber_UbiddingpbBaseAdnConfig = 1,
};

/**
 * Saas 代码位策略
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdnConfig : UbiXGPBMessage

/** 公共结构 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseAdnConfig *ubiddingpbBaseAdnConfig;
/** Test to see if @c ubiddingpbBaseAdnConfig has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbBaseAdnConfig;

@end

#pragma mark - UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdCache

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdCache_FieldNumber) {
  UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdCache_FieldNumber_UbiddingpbcacheLimitSize = 1,
};

UbiX_GPB_FINAL @interface UBiddingPbResponse_UBiddingPbConfigResponse_UBiddingPbSlotConfig_UBiddingPbAdCache : UbiXGPBMessage

/** 缓存容器最大数量，默认为5个，0代表不缓存 */
@property(nonatomic, readwrite) int32_t ubiddingpbcacheLimitSize;

@end

#pragma mark - UBiddingPbResponse_UADXPbConfigResponse

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UADXPbConfigResponse_FieldNumber) {
  UBiddingPbResponse_UADXPbConfigResponse_FieldNumber_UbiddingpbBaseConfigs = 1,
  UBiddingPbResponse_UADXPbConfigResponse_FieldNumber_UbiddingpbSlotConfigsArray = 2,
};

/**
 * UADX 广告策略
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UADXPbConfigResponse : UbiXGPBMessage

/** 公共结构 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseConfigResponse *ubiddingpbBaseConfigs;
/** Test to see if @c ubiddingpbBaseConfigs has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbBaseConfigs;

/** 策略模块 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig*> *ubiddingpbSlotConfigsArray;
/** The number of items in @c ubiddingpbSlotConfigsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbSlotConfigsArray_Count;

@end

#pragma mark - UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_FieldNumber) {
  UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_FieldNumber_UbiddingpbBaseSlotConfig = 1,
  UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_FieldNumber_UbiddingpbAdSourcesArray = 2,
  UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_FieldNumber_UbiddingpbAbTest = 3,
  UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_FieldNumber_UbiddingpbAdMode = 4,
  UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_FieldNumber_UbiddingpbFixedPrice = 5,
};

/**
 * UADX 流量组策略
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig : UbiXGPBMessage

/** 公共结构 内部有UADX流量组id */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseSlotConfig *ubiddingpbBaseSlotConfig;
/** Test to see if @c ubiddingpbBaseSlotConfig has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbBaseSlotConfig;

/** 广告源列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_UADXPbAdnConfig*> *ubiddingpbAdSourcesArray;
/** The number of items in @c ubiddingpbAdSourcesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbAdSourcesArray_Count;

/** ABTest */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingBaseABTest *ubiddingpbAbTest;
/** Test to see if @c ubiddingpbAbTest has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbAbTest;

/** 合作模式 1= bidding 2= PD */
@property(nonatomic, readwrite) int32_t ubiddingpbAdMode;

/** PD合作模式时 下游出价 */
@property(nonatomic, readwrite) uint64_t ubiddingpbFixedPrice;

@end

#pragma mark - UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_UADXPbAdnConfig

typedef UbiX_GPB_ENUM(UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_UADXPbAdnConfig_FieldNumber) {
  UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_UADXPbAdnConfig_FieldNumber_UbiddingpbBaseAdnConfig = 1,
  UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_UADXPbAdnConfig_FieldNumber_UbiddingpbMR = 2,
};

/**
 * UADX 代码位策略
 **/
UbiX_GPB_FINAL @interface UBiddingPbResponse_UADXPbConfigResponse_UADXPbSlotConfig_UADXPbAdnConfig : UbiXGPBMessage

/** 公共结构 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseAdnConfig *ubiddingpbBaseAdnConfig;
/** Test to see if @c ubiddingpbBaseAdnConfig has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingpbBaseAdnConfig;

/** 利润率 margin_rate */
@property(nonatomic, readwrite) int32_t ubiddingpbMR;

@end

#pragma mark - UBiddingPbBaseConfigResponse

typedef UbiX_GPB_ENUM(UBiddingPbBaseConfigResponse_FieldNumber) {
  UBiddingPbBaseConfigResponse_FieldNumber_UbiddingpbStatusCode = 1,
  UBiddingPbBaseConfigResponse_FieldNumber_UbiddingpbPubAccountId = 2,
};

/**
 * 公共广告策略结构
 **/
UbiX_GPB_FINAL @interface UBiddingPbBaseConfigResponse : UbiXGPBMessage

/** 状态码 0正常 非0对应错误码，例如app不存在 */
@property(nonatomic, readwrite) int32_t ubiddingpbStatusCode;

/** 开发者账户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbPubAccountId;

@end

#pragma mark - UBiddingPbBaseSlotConfig

typedef UbiX_GPB_ENUM(UBiddingPbBaseSlotConfig_FieldNumber) {
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbSlotId = 1,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbStatusCode = 2,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbTrafficGroupMd5 = 3,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbConfigChanged = 4,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbAdType = 5,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbTotalReqTimeout = 6,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbLevelReqTimeout = 7,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbTrafficGroupId = 8,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbVideoMute = 9,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbVideoPlayNetType = 10,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbConfigCacheExpireTime = 11,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbBidFloor = 12,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbServerExtParams = 13,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbCFRate = 14,
  UBiddingPbBaseSlotConfig_FieldNumber_UbiddingpbDIAdnIdArray = 15,
};

/**
 * 公共流量组策略结构
 **/
UbiX_GPB_FINAL @interface UBiddingPbBaseSlotConfig : UbiXGPBMessage

/** 聚合广告位id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbSlotId;

/** 聚合广告位状态 0:有策略 非0:无策略 */
@property(nonatomic, readwrite) int32_t ubiddingpbStatusCode;

/** 广告配置的MD5唯一值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbTrafficGroupMd5;

/** 是否需要更新流量组 */
@property(nonatomic, readwrite) BOOL ubiddingpbConfigChanged;

/** 广告类型 */
@property(nonatomic, readwrite) int32_t ubiddingpbAdType;

/** 总超时时间限制 单位 ms；4.0.0：UADX下发无值，UADX直接使用Saas值； */
@property(nonatomic, readwrite) int32_t ubiddingpbTotalReqTimeout;

/** 单次并发请求时间限制（单位ms） */
@property(nonatomic, readwrite) int32_t ubiddingpbLevelReqTimeout;

/** 流量组id */
@property(nonatomic, readwrite) int32_t ubiddingpbTrafficGroupId;

/** 是否静音播放， 1=广告源默认 2=静音 3=不静音 */
@property(nonatomic, readwrite) int32_t ubiddingpbVideoMute;

/** 视频播放网络状态，1=广告源默认，2=Wi-Fi+移动网络、3=仅Wi-Fi、4:任何网络都不播放 */
@property(nonatomic, readwrite) int32_t ubiddingpbVideoPlayNetType;

/** 配置缓存有效期，单位秒 */
@property(nonatomic, readwrite) int32_t ubiddingpbConfigCacheExpireTime;

/** bidding过滤底价（单位/分） */
@property(nonatomic, readwrite) uint64_t ubiddingpbBidFloor;

/** 天权打点透传 本期仅AB实验 非必填 服务端扩展参数 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbServerExtParams;

/** 点击拦截比例 */
@property(nonatomic, readwrite) int32_t ubiddingpbCFRate;

/** 不支持初始化的广告源 */
@property(nonatomic, readwrite, strong, null_resettable) UbiXGPBInt32Array *ubiddingpbDIAdnIdArray;
/** The number of items in @c ubiddingpbDIAdnIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbDIAdnIdArray_Count;

@end

#pragma mark - UBiddingBaseABTest

typedef UbiX_GPB_ENUM(UBiddingBaseABTest_FieldNumber) {
  UBiddingBaseABTest_FieldNumber_UbiddingpbAbTest = 1,
  UBiddingBaseABTest_FieldNumber_UbiddingpbAbtestGroupId = 2,
};

UbiX_GPB_FINAL @interface UBiddingBaseABTest : UbiXGPBMessage

/** 服务端下发，AB实验ID。（预留字段，默认为空） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAbTest;

/** 服务端下发，AB实验用户分组ID。（预留字段，默认为空） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAbtestGroupId;

@end

#pragma mark - UBiddingPbBaseAdnConfig

typedef UbiX_GPB_ENUM(UBiddingPbBaseAdnConfig_FieldNumber) {
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbAppAdnId = 1,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbSlotId = 2,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbBidPrice = 3,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbRenderType = 4,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbBidType = 5,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbLevelIndex = 6,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbExt = 7,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbAdnSlotInnerId = 8,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbAdnAdType = 9,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbAdnAdRenderType = 10,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbRenderStyleType = 11,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbInteractionType = 12,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbRdVyType = 13,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbRdCnSeconds = 14,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbCrType = 15,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbCrLiCount = 16,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbCrSSeconds = 17,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbCrPcV = 18,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbCrRegArray = 19,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbCrSkRegArray = 20,
  UBiddingPbBaseAdnConfig_FieldNumber_UbiddingpbDismissSetting = 21,
};

/**
 * 公共代码位策略结构
 **/
UbiX_GPB_FINAL @interface UBiddingPbBaseAdnConfig : UbiXGPBMessage

/** app 广告源关系 id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAppAdnId;

/** 广告源slot id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbSlotId;

/** 预估出价 - 只对waterfall形式时下发 单位:分 */
@property(nonatomic, readwrite) uint64_t ubiddingpbBidPrice;

/** 渲染方式 1:模板 2:自渲染 */
@property(nonatomic, readwrite) int32_t ubiddingpbRenderType;

/** 竞价类型 1:in-app-bidding 2:waterfall */
@property(nonatomic, readwrite) int32_t ubiddingpbBidType;

/** 广告源所属的转发层级，从1开始，bidding层为1 */
@property(nonatomic, readwrite) int32_t ubiddingpbLevelIndex;

/** 通用扩展字段，由客户端解析 代码位高级配置 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbExt;

/** 代码位资产id */
@property(nonatomic, readwrite) int64_t ubiddingpbAdnSlotInnerId;

/** ADN广告类型 值同ubiddingpb_ad_type */
@property(nonatomic, readwrite) int32_t ubiddingpbAdnAdType;

/** ADN模板类型 1:模板 2:自渲染 */
@property(nonatomic, readwrite) int32_t ubiddingpbAdnAdRenderType;

/** 仅自渲染-映射模板样式(开屏模版选择:“101”;  插屏模版选择:“201：半屏竖版16x9； 202：半屏横版9x16； 203：全屏 ”;  激励模版选择:“301”;  横幅模版选择:“401：横幅32x5”; */
@property(nonatomic, readwrite) int32_t ubiddingpbRenderStyleType;

/** 仅自渲染-交互样式 0：默认提示区域可点；1:全局可点（类似CTR常规） */
@property(nonatomic, readwrite) int32_t ubiddingpbInteractionType;

/** reward_verify_type 仅自渲染-激励回调时机 0:广告曝光关闭（本期只有模板映射支持且只支持这种）1:播放完成（自渲染映射默认）；2：仅点击广告；3：播放完成或点击， 4：播放完成或5秒停留弹窗 */
@property(nonatomic, readwrite) int32_t ubiddingpbRdVyType;

/** reward_countdown_seconds 仅自渲染-激励播放时长 单位秒 */
@property(nonatomic, readwrite) int32_t ubiddingpbRdCnSeconds;

/** ctr_type CTR 0:无配置 1:CTR常规 2:CTR稳准狠 3:信息流自渲染点滑 4:弹窗提示自动跳转 5:静默自动跳转 */
@property(nonatomic, readwrite) int32_t ubiddingpbCrType;

/** ctr_limit_count 代码位下设备ID当天内 CTR 最多累计优化次数,0点清空， 0代表不限制 */
@property(nonatomic, readwrite) int32_t ubiddingpbCrLiCount;

/** ctr_step_seconds 代码位下设备ID CTR 优化生效的间隔。单位：秒 */
@property(nonatomic, readwrite) int32_t ubiddingpbCrSSeconds;

/** ctr_percent_value 点击率值 万分之一单位 */
@property(nonatomic, readwrite) int32_t ubiddingpbCrPcV;

/** ctr_region android 点击区域 [x1,x2,y1,y2], 0<x<=360 0<y<=640 */
@property(nonatomic, readwrite, strong, null_resettable) UbiXGPBInt32Array *ubiddingpbCrRegArray;
/** The number of items in @c ubiddingpbCrRegArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbCrRegArray_Count;

/** ctr_skip_region android 跳过区域 [x1,x2,y1,y2], 0<x<=360 0<y<=640 */
@property(nonatomic, readwrite, strong, null_resettable) UbiXGPBInt32Array *ubiddingpbCrSkRegArray;
/** The number of items in @c ubiddingpbCrSkRegArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbCrSkRegArray_Count;

/** 点击延时dismiss_setting，仅Android开屏，1：与第一次点击间隔为2000ms延时回调开屏dismiss。 */
@property(nonatomic, readwrite) int32_t ubiddingpbDismissSetting;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
