// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ubidding_ad_sdk_daq.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/UbiXGPBProtocolBuffers.h>
#else
#import <UbiXDaq/UbiXGPBProtocolBuffers.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UADXPbABTest;
@class UADXPbAdNetwork;
@class UADXPbAdRequest;
@class UADXPbBidResult;
@class UADXPbEvent;
@class UADXPbMaterial;
@class UADXPbMaterialImage;
@class UADXPbMaterialVideo;
@class UBiddingBasePbEvent;
@class UBiddingPbABTest;
@class UBiddingPbAdNetwork;
@class UBiddingPbAdRequest;
@class UBiddingPbBaseAdNetwork;
@class UBiddingPbBaseAdRequest;
@class UBiddingPbBidResult;
@class UBiddingPbEvent;
@class UBiddingPbMaterial;
@class UBiddingPbMaterialImage;
@class UBiddingPbMaterialVideo;
@class UBiddingPbMonitor;
@class UBiddingPbMonitor_UBiddingPbMonitorError;
@class UBiddingPbPrivacyConfig;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UbiddingAdSdkDaqRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (UbiXGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c UbiXGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
UbiX_GPB_FINAL @interface UbiddingAdSdkDaqRoot : UbiXGPBRootObject
@end

#pragma mark - UBiddingPbAdSDKDaq

typedef UbiX_GPB_ENUM(UBiddingPbAdSDKDaq_FieldNumber) {
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingClientId = 1,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingAppId = 2,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingUploadTime = 3,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingAdReqsArray = 4,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingEnv = 5,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingOsType = 6,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingOsVersion = 7,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingSdkVersion = 8,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingAppVersion = 9,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingDeviceBrand = 10,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingDeviceModel = 11,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingPackageName = 12,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingAndroidId = 13,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingIdfv = 14,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingOaid = 15,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingIdfa = 16,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingUid = 17,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingChannel = 18,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingSubChannel = 19,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingIsSubscriber = 20,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingPubSegmentId = 21,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingEventsArray = 22,
  UBiddingPbAdSDKDaq_FieldNumber_MonitorArray = 23,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingPubAccountId = 24,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingUb = 25,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingSm = 26,
  UBiddingPbAdSDKDaq_FieldNumber_UbiddingUadxAdReqsArray = 27,
};

UbiX_GPB_FINAL @interface UBiddingPbAdSDKDaq : UbiXGPBMessage

/** # 公参 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingClientId;

/** 必填 APP ID， 媒体在ubix侧注册时生成的应用ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAppId;

/** 上报时间，毫秒，时间戳 */
@property(nonatomic, readwrite) int64_t ubiddingUploadTime;

/** 必填 Saas广告请求 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbAdRequest*> *ubiddingAdReqsArray;
/** The number of items in @c ubiddingAdReqsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingAdReqsArray_Count;

/** 环境 0：正式，1：测试 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingEnv;

/** 操作系统类型，0: Unknown, 1: Android, 2: iOS */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingOsType;

/** 操作系统版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingOsVersion;

/** SDK版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingSdkVersion;

/** 媒体App版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAppVersion;

/** 设备品牌 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDeviceBrand;

/** 设备型号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDeviceModel;

/** 应用包名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingPackageName;

/** Android id，Android上报，计算DAU使用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAndroidId;

/** idfv，iOS上报，计算DAU使用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingIdfv;

/** oaid，Android上报 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingOaid;

/** idfa，iOS上报 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingIdfa;

/** 用户在媒体上注册的ID。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingUid;

/** 渠道，由开发者自定义 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingChannel;

/** 子渠道，由开发者自定义 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingSubChannel;

/** 付费用户。0: 未知；1: 否；2: 是 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingIsSubscriber;

/** 开发者的流量分组ID或者标签ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingPubSegmentId;

/** Saas事件列表，跟单次广告请求无关， 如： 聚合初始化 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbEvent*> *ubiddingEventsArray;
/** The number of items in @c ubiddingEventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingEventsArray_Count;

/** 崩溃信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbMonitor*> *monitorArray;
/** The number of items in @c monitorArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger monitorArray_Count;

/** 开发者账户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingPubAccountId;

/** 监测USB调试，不设值-未监测，1-未打开、2-打开, 仅Android */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingUb;

/** 监测SIM卡，不设值-未监测，1-未插入、2-已插入, Android+iOS */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingSm;

/** 必填 UADX广告请求 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UADXPbAdRequest*> *ubiddingUadxAdReqsArray;
/** The number of items in @c ubiddingUadxAdReqsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingUadxAdReqsArray_Count;

@end

#pragma mark - UBiddingPbMonitor

typedef UbiX_GPB_ENUM(UBiddingPbMonitor_FieldNumber) {
  UBiddingPbMonitor_FieldNumber_UbiddingMonitorType = 1,
  UBiddingPbMonitor_FieldNumber_UbiddingLaunchTime = 2,
  UBiddingPbMonitor_FieldNumber_UbiddingMonitorError = 3,
};

UbiX_GPB_FINAL @interface UBiddingPbMonitor : UbiXGPBMessage

/** 崩溃类型 1:错误监控 2:其他 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingMonitorType;

/** app启动时间，毫秒，时间戳 */
@property(nonatomic, readwrite) int64_t ubiddingLaunchTime;

@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbMonitor_UBiddingPbMonitorError *ubiddingMonitorError;
/** Test to see if @c ubiddingMonitorError has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingMonitorError;

@end

#pragma mark - UBiddingPbMonitor_UBiddingPbMonitorError

typedef UbiX_GPB_ENUM(UBiddingPbMonitor_UBiddingPbMonitorError_FieldNumber) {
  UBiddingPbMonitor_UBiddingPbMonitorError_FieldNumber_UbiddingErrorType = 1,
  UBiddingPbMonitor_UBiddingPbMonitorError_FieldNumber_UbiddingErrorClassification = 2,
  UBiddingPbMonitor_UBiddingPbMonitorError_FieldNumber_UbiddingErrorTime = 3,
  UBiddingPbMonitor_UBiddingPbMonitorError_FieldNumber_UbiddingErrorThread = 4,
  UBiddingPbMonitor_UBiddingPbMonitorError_FieldNumber_UbiddingErrorStack = 5,
};

UbiX_GPB_FINAL @interface UBiddingPbMonitor_UBiddingPbMonitorError : UbiXGPBMessage

/** 错误类型 1:java 2:native 3:anr 4:Exception */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingErrorType;

/** 错误分类 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingErrorClassification;

/** 发生时，毫秒，时间戳 */
@property(nonatomic, readwrite) int64_t ubiddingErrorTime;

/** 错误时所在线程 主线程:main */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingErrorThread;

/** 堆栈信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingErrorStack;

@end

#pragma mark - UBiddingPbEvent

typedef UbiX_GPB_ENUM(UBiddingPbEvent_FieldNumber) {
  UBiddingPbEvent_FieldNumber_UbiddingBaseEvent = 1,
  UBiddingPbEvent_FieldNumber_UbiddingAdnMaterials = 2,
  UBiddingPbEvent_FieldNumber_UbiddingPrivacyConfig = 3,
  UBiddingPbEvent_FieldNumber_UbiddingUadxRequest = 4,
  UBiddingPbEvent_FieldNumber_UbiddingBidResult = 5,
};

/**
 * Saas 事件埋点
 **/
UbiX_GPB_FINAL @interface UBiddingPbEvent : UbiXGPBMessage

/** 公共结构 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingBasePbEvent *ubiddingBaseEvent;
/** Test to see if @c ubiddingBaseEvent has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingBaseEvent;

/** 素材，监控/展示上报 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbMaterial *ubiddingAdnMaterials;
/** Test to see if @c ubiddingAdnMaterials has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingAdnMaterials;

/** 隐私配置开关，如传感器开关 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbPrivacyConfig *ubiddingPrivacyConfig;
/** Test to see if @c ubiddingPrivacyConfig has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingPrivacyConfig;

/** Saas附带UADX竞胜ADN信息; Saas填充、展示、点击时有值 */
@property(nonatomic, readwrite, strong, null_resettable) UADXPbAdRequest *ubiddingUadxRequest;
/** Test to see if @c ubiddingUadxRequest has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingUadxRequest;

/** 竞价结果回传专属字段，仅 4010(竞胜)/4011(竞败) 事件填充 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBidResult *ubiddingBidResult;
/** Test to see if @c ubiddingBidResult has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingBidResult;

@end

#pragma mark - UBiddingPbPrivacyConfig

typedef UbiX_GPB_ENUM(UBiddingPbPrivacyConfig_FieldNumber) {
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingLocation = 1,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingAppList = 2,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingPhoneState = 3,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingWifiState = 4,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingWriteExternal = 5,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingCanGetOaid = 6,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingDevOaid = 7,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingCanGetAndroidId = 8,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingDevAndroidId = 9,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingMacAddress = 10,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingLimitPersonalAd = 11,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingProgramRecommend = 12,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingSensor = 13,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingCanReadIdfa = 14,
  UBiddingPbPrivacyConfig_FieldNumber_UbiddingCustomIdfa = 15,
};

UbiX_GPB_FINAL @interface UBiddingPbPrivacyConfig : UbiXGPBMessage

/** 是否允许获取 location：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingLocation;

/** 是否允许获取 应用列表：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAppList;

/** 是否允许获取 phone_state：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingPhoneState;

/** 是否允许获取 wifi_state：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingWifiState;

/** 是否允许获取 写外存：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingWriteExternal;

/** 是否允许获取 oaid：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingCanGetOaid;

/** 开发者传入的设备 oaid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDevOaid;

/** 是否允许获取 android_id：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingCanGetAndroidId;

/** 开发者传入的设备 android_id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDevAndroidId;

/** 是否允许获取 mac_address：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingMacAddress;

/** 限制个性化推荐：1 限制，0 :不限制 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingLimitPersonalAd;

/** 程序化推荐开关：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingProgramRecommend;

/** 开发者传入的传感器开关：1=允许，0=不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingSensor;

/** ios 是否允许获取 idfa：1 允许，0 :不允许 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingCanReadIdfa;

/** ios 开发者传入的idfa */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingCustomIdfa;

@end

#pragma mark - UBiddingPbAdRequest

typedef UbiX_GPB_ENUM(UBiddingPbAdRequest_FieldNumber) {
  UBiddingPbAdRequest_FieldNumber_UbiddingBaseAdRequest = 1,
  UBiddingPbAdRequest_FieldNumber_UbiddingAdnsArray = 2,
  UBiddingPbAdRequest_FieldNumber_UbiddingEventsArray = 3,
  UBiddingPbAdRequest_FieldNumber_UbiddingAbtest = 4,
};

/**
 * Saas 广告请求埋点
 **/
UbiX_GPB_FINAL @interface UBiddingPbAdRequest : UbiXGPBMessage

/** 公共结构 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseAdRequest *ubiddingBaseAdRequest;
/** Test to see if @c ubiddingBaseAdRequest has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingBaseAdRequest;

/** # 广告/广告网络相关事件 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbAdNetwork*> *ubiddingAdnsArray;
/** The number of items in @c ubiddingAdnsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingAdnsArray_Count;

/** 事件列表，策略 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbEvent*> *ubiddingEventsArray;
/** The number of items in @c ubiddingEventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingEventsArray_Count;

/** ABTest */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbABTest *ubiddingAbtest;
/** Test to see if @c ubiddingAbtest has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingAbtest;

@end

#pragma mark - UBiddingPbMaterial

typedef UbiX_GPB_ENUM(UBiddingPbMaterial_FieldNumber) {
  UBiddingPbMaterial_FieldNumber_UbiddingImagesArray = 1,
  UBiddingPbMaterial_FieldNumber_UbiddingVideosArray = 2,
  UBiddingPbMaterial_FieldNumber_UbiddingAppName = 3,
  UBiddingPbMaterial_FieldNumber_UbiddingTitle = 4,
  UBiddingPbMaterial_FieldNumber_UbiddingDescription = 5,
  UBiddingPbMaterial_FieldNumber_UbiddingTargetURL = 6,
  UBiddingPbMaterial_FieldNumber_UbiddingDownloadURL = 7,
  UBiddingPbMaterial_FieldNumber_UbiddingDeeplinkURL = 8,
  UBiddingPbMaterial_FieldNumber_UbiddingPackageName = 9,
  UBiddingPbMaterial_FieldNumber_UbiddingUniversalLink = 10,
  UBiddingPbMaterial_FieldNumber_UbiddingExtra = 11,
};

UbiX_GPB_FINAL @interface UBiddingPbMaterial : UbiXGPBMessage

/** 图片素材 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbMaterialImage*> *ubiddingImagesArray;
/** The number of items in @c ubiddingImagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingImagesArray_Count;

/** 视频素材 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbMaterialVideo*> *ubiddingVideosArray;
/** The number of items in @c ubiddingVideosArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingVideosArray_Count;

/** 素材app名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAppName;

/** 标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingTitle;

/** 描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDescription;

/** 落地页url，端上对应 landing_page_url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingTargetURL;

/** 下载地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDownloadURL;

/** 跳转地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDeeplinkURL;

/** 预算包名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingPackageName;

/** ios跳转地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingUniversalLink;

/** 拓展参数。json格式；仅Saas上报，UADX不报；Saas上报时附带了UADX信息进行关联 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingExtra;

@end

#pragma mark - UBiddingPbMaterialImage

typedef UbiX_GPB_ENUM(UBiddingPbMaterialImage_FieldNumber) {
  UBiddingPbMaterialImage_FieldNumber_UbiddingImageId = 1,
  UBiddingPbMaterialImage_FieldNumber_UbiddingImageURL = 2,
  UBiddingPbMaterialImage_FieldNumber_UbiddingMaterialRulerId = 3,
  UBiddingPbMaterialImage_FieldNumber_UbiddingImageHeight = 4,
  UBiddingPbMaterialImage_FieldNumber_UbiddingImageWidth = 5,
};

UbiX_GPB_FINAL @interface UBiddingPbMaterialImage : UbiXGPBMessage

/** 图片 url md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingImageId;

/** 图片 url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingImageURL;

/** 素材审核id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingMaterialRulerId;

/** 图片高度 */
@property(nonatomic, readwrite) int32_t ubiddingImageHeight;

/** 图片宽度 */
@property(nonatomic, readwrite) int32_t ubiddingImageWidth;

@end

#pragma mark - UBiddingPbMaterialVideo

typedef UbiX_GPB_ENUM(UBiddingPbMaterialVideo_FieldNumber) {
  UBiddingPbMaterialVideo_FieldNumber_UbiddingVideoId = 1,
  UBiddingPbMaterialVideo_FieldNumber_UbiddingVideoURL = 2,
  UBiddingPbMaterialVideo_FieldNumber_UbiddingCoverImgURL = 3,
  UBiddingPbMaterialVideo_FieldNumber_UbiddingMaterialRulerId = 4,
  UBiddingPbMaterialVideo_FieldNumber_UbiddingVideoHeight = 5,
  UBiddingPbMaterialVideo_FieldNumber_UbiddingVideoWidth = 6,
  UBiddingPbMaterialVideo_FieldNumber_UbiddingVideoDuration = 7,
};

UbiX_GPB_FINAL @interface UBiddingPbMaterialVideo : UbiXGPBMessage

/** 视频 url md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingVideoId;

/** 视频 url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingVideoURL;

/** 封面图url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingCoverImgURL;

/** 素材审核id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingMaterialRulerId;

/** 视频高度 */
@property(nonatomic, readwrite) int32_t ubiddingVideoHeight;

/** 视频宽度 */
@property(nonatomic, readwrite) int32_t ubiddingVideoWidth;

/** 视频时长；单位：ms */
@property(nonatomic, readwrite) int32_t ubiddingVideoDuration;

@end

#pragma mark - UBiddingPbBidResult

typedef UbiX_GPB_ENUM(UBiddingPbBidResult_FieldNumber) {
  UBiddingPbBidResult_FieldNumber_UbiddingBidSecondPrice = 1,
  UBiddingPbBidResult_FieldNumber_UbiddingBidWinPrice = 2,
  UBiddingPbBidResult_FieldNumber_UbiddingBidWinAdnId = 3,
  UBiddingPbBidResult_FieldNumber_UbiddingBidLossReason = 4,
  UBiddingPbBidResult_FieldNumber_UbiddingBidWinAdsource = 5,
  UBiddingPbBidResult_FieldNumber_UbiddingBidWinAdtitle = 6,
};

/**
 * Saas 竞价结果回传专属信息(4010 竞胜 / 4011 竞败 事件填充)
 * 注：字段名/字段号为占位，待与服务端最终确认
 **/
UbiX_GPB_FINAL @interface UBiddingPbBidResult : UbiXGPBMessage

/** 竞胜时的次高价(竞败方最高价)，单位分 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidSecondPrice;

/** 竞败时竞胜方的最高价，单位分 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidWinPrice;

/** 竞败时竞胜方平台 id（平台枚举值，如 16=天璇；对应 config 的 ubiddingpb_adn_id） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidWinAdnId;

/** 竞败原因 1:底价过滤 2:广告竞价失败 3:广告返回超时 4:素材屏蔽/审核未通过 5:广告失效或过期 6:其它(兜底) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidLossReason;

/** 竞败时竞胜方广告主名称(选填) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidWinAdsource;

/** 竞败时竞胜方广告标题(选填) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidWinAdtitle;

@end

#pragma mark - UBiddingPbABTest

typedef UbiX_GPB_ENUM(UBiddingPbABTest_FieldNumber) {
  UBiddingPbABTest_FieldNumber_UbiddingAbtestId = 1,
  UBiddingPbABTest_FieldNumber_UbiddingAbtestGroupId = 2,
};

UbiX_GPB_FINAL @interface UBiddingPbABTest : UbiXGPBMessage

/** 服务端下发，AB实验ID。（预留字段，默认为空） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAbtestId;

/** 服务端下发，AB实验用户分组ID。（预留字段，默认为空） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAbtestGroupId;

@end

#pragma mark - UBiddingPbAdNetwork

typedef UbiX_GPB_ENUM(UBiddingPbAdNetwork_FieldNumber) {
  UBiddingPbAdNetwork_FieldNumber_UbiddingBaseAdNetwork = 1,
  UBiddingPbAdNetwork_FieldNumber_UbiddingEventsArray = 2,
};

/**
 * Saas 广告源埋点
 **/
UbiX_GPB_FINAL @interface UBiddingPbAdNetwork : UbiXGPBMessage

/** # 广告/广告网络相关事件 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseAdNetwork *ubiddingBaseAdNetwork;
/** Test to see if @c ubiddingBaseAdNetwork has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingBaseAdNetwork;

/** 事件列表，转发/填充/展/点/消事件 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbEvent*> *ubiddingEventsArray;
/** The number of items in @c ubiddingEventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingEventsArray_Count;

@end

#pragma mark - UADXPbEvent

typedef UbiX_GPB_ENUM(UADXPbEvent_FieldNumber) {
  UADXPbEvent_FieldNumber_UbiddingBaseEvent = 1,
  UADXPbEvent_FieldNumber_UbiddingAdnMaterials = 2,
  UADXPbEvent_FieldNumber_UbiddingBidResult = 3,
};

/**
 * UADX 事件埋点
 **/
UbiX_GPB_FINAL @interface UADXPbEvent : UbiXGPBMessage

/** 公共结构 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingBasePbEvent *ubiddingBaseEvent;
/** Test to see if @c ubiddingBaseEvent has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingBaseEvent;

/** 素材，监控/展示上报 */
@property(nonatomic, readwrite, strong, null_resettable) UADXPbMaterial *ubiddingAdnMaterials;
/** Test to see if @c ubiddingAdnMaterials has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingAdnMaterials;

/** 竞价结果回传专属字段，仅 104010(竞胜)/104011(竞败) 事件填充 */
@property(nonatomic, readwrite, strong, null_resettable) UADXPbBidResult *ubiddingBidResult;
/** Test to see if @c ubiddingBidResult has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingBidResult;

@end

#pragma mark - UADXPbMaterial

typedef UbiX_GPB_ENUM(UADXPbMaterial_FieldNumber) {
  UADXPbMaterial_FieldNumber_UbiddingImagesArray = 1,
  UADXPbMaterial_FieldNumber_UbiddingVideosArray = 2,
  UADXPbMaterial_FieldNumber_UbiddingAppName = 3,
  UADXPbMaterial_FieldNumber_UbiddingTitle = 4,
  UADXPbMaterial_FieldNumber_UbiddingDescription = 5,
  UADXPbMaterial_FieldNumber_UbiddingTargetURL = 6,
  UADXPbMaterial_FieldNumber_UbiddingDownloadURL = 7,
  UADXPbMaterial_FieldNumber_UbiddingDeeplinkURL = 8,
  UADXPbMaterial_FieldNumber_UbiddingPackageName = 9,
  UADXPbMaterial_FieldNumber_UbiddingUniversalLink = 10,
};

UbiX_GPB_FINAL @interface UADXPbMaterial : UbiXGPBMessage

/** 图片素材 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UADXPbMaterialImage*> *ubiddingImagesArray;
/** The number of items in @c ubiddingImagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingImagesArray_Count;

/** 视频素材 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UADXPbMaterialVideo*> *ubiddingVideosArray;
/** The number of items in @c ubiddingVideosArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingVideosArray_Count;

/** 素材app名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAppName;

/** 标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingTitle;

/** 描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDescription;

/** 落地页url，端上对应 landing_page_url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingTargetURL;

/** 下载地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDownloadURL;

/** 跳转地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingDeeplinkURL;

/** 预算包名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingPackageName;

/** ios跳转地址，Android端不赋值，保留字段定义以与服务端/iOS协议对齐 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingUniversalLink;

@end

#pragma mark - UADXPbMaterialImage

typedef UbiX_GPB_ENUM(UADXPbMaterialImage_FieldNumber) {
  UADXPbMaterialImage_FieldNumber_UbiddingImageId = 1,
  UADXPbMaterialImage_FieldNumber_UbiddingImageURL = 2,
  UADXPbMaterialImage_FieldNumber_UbiddingMaterialRulerId = 3,
  UADXPbMaterialImage_FieldNumber_UbiddingImageHeight = 4,
  UADXPbMaterialImage_FieldNumber_UbiddingImageWidth = 5,
};

UbiX_GPB_FINAL @interface UADXPbMaterialImage : UbiXGPBMessage

/** 图片 url md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingImageId;

/** 图片 url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingImageURL;

/** 素材审核id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingMaterialRulerId;

/** 图片高度 */
@property(nonatomic, readwrite) int32_t ubiddingImageHeight;

/** 图片宽度 */
@property(nonatomic, readwrite) int32_t ubiddingImageWidth;

@end

#pragma mark - UADXPbMaterialVideo

typedef UbiX_GPB_ENUM(UADXPbMaterialVideo_FieldNumber) {
  UADXPbMaterialVideo_FieldNumber_UbiddingVideoId = 1,
  UADXPbMaterialVideo_FieldNumber_UbiddingVideoURL = 2,
  UADXPbMaterialVideo_FieldNumber_UbiddingCoverImgURL = 3,
  UADXPbMaterialVideo_FieldNumber_UbiddingMaterialRulerId = 4,
  UADXPbMaterialVideo_FieldNumber_UbiddingVideoHeight = 5,
  UADXPbMaterialVideo_FieldNumber_UbiddingVideoWidth = 6,
  UADXPbMaterialVideo_FieldNumber_UbiddingVideoDuration = 7,
};

UbiX_GPB_FINAL @interface UADXPbMaterialVideo : UbiXGPBMessage

/** 视频 url md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingVideoId;

/** 视频 url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingVideoURL;

/** 封面图url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingCoverImgURL;

/** 素材审核id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingMaterialRulerId;

/** 视频高度 */
@property(nonatomic, readwrite) int32_t ubiddingVideoHeight;

/** 视频宽度 */
@property(nonatomic, readwrite) int32_t ubiddingVideoWidth;

/** 视频时长；单位：ms */
@property(nonatomic, readwrite) int32_t ubiddingVideoDuration;

@end

#pragma mark - UADXPbBidResult

typedef UbiX_GPB_ENUM(UADXPbBidResult_FieldNumber) {
  UADXPbBidResult_FieldNumber_UbiddingBidSecondPrice = 1,
  UADXPbBidResult_FieldNumber_UbiddingBidWinPrice = 2,
  UADXPbBidResult_FieldNumber_UbiddingBidWinAdnId = 3,
  UADXPbBidResult_FieldNumber_UbiddingBidLossReason = 4,
  UADXPbBidResult_FieldNumber_UbiddingBidWinAdsource = 5,
  UADXPbBidResult_FieldNumber_UbiddingBidWinAdtitle = 6,
};

/**
 * UADX 竞价结果回传专属信息(104010 竞胜 / 104011 竞败 事件填充)
 * 字段集合与 UBiddingPbBidResult 一致(同 material 拆 Saas/UADX 两套的惯例)；字段名/字段号为占位，待与服务端最终确认
 **/
UbiX_GPB_FINAL @interface UADXPbBidResult : UbiXGPBMessage

/** 竞胜时的次高价(竞败方最高价)，单位分 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidSecondPrice;

/** 竞败时竞胜方的最高价，单位分 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidWinPrice;

/** 竞败时竞胜方平台 id（平台枚举值，如 16=天璇；对应 config 的 ubiddingpb_adn_id） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidWinAdnId;

/** 竞败原因 1:底价过滤 2:广告竞价失败 3:广告返回超时 4:素材屏蔽/审核未通过 5:广告失效或过期 6:其它(兜底) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidLossReason;

/** 竞败时竞胜方广告主名称(选填) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidWinAdsource;

/** 竞败时竞胜方广告标题(选填) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidWinAdtitle;

@end

#pragma mark - UADXPbAdRequest

typedef UbiX_GPB_ENUM(UADXPbAdRequest_FieldNumber) {
  UADXPbAdRequest_FieldNumber_UbiddingBaseAdRequest = 1,
  UADXPbAdRequest_FieldNumber_UbiddingSaasAdRequestId = 2,
  UADXPbAdRequest_FieldNumber_UbiddingAdnsArray = 3,
  UADXPbAdRequest_FieldNumber_UbiddingEventsArray = 4,
  UADXPbAdRequest_FieldNumber_UbiddingAbtest = 5,
  UADXPbAdRequest_FieldNumber_UbiddingAdMode = 6,
  UADXPbAdRequest_FieldNumber_UbiddingFixedPrice = 7,
};

/**
 * UADX 广告请求埋点
 **/
UbiX_GPB_FINAL @interface UADXPbAdRequest : UbiXGPBMessage

/** 公共结构 内部有UADX 广告请求id */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseAdRequest *ubiddingBaseAdRequest;
/** Test to see if @c ubiddingBaseAdRequest has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingBaseAdRequest;

/** Saas广告请求id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingSaasAdRequestId;

/** # 广告/广告网络相关事件 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UADXPbAdNetwork*> *ubiddingAdnsArray;
/** The number of items in @c ubiddingAdnsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingAdnsArray_Count;

/** 事件列表，策略 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UADXPbEvent*> *ubiddingEventsArray;
/** The number of items in @c ubiddingEventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingEventsArray_Count;

/** ABTest */
@property(nonatomic, readwrite, strong, null_resettable) UADXPbABTest *ubiddingAbtest;
/** Test to see if @c ubiddingAbtest has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingAbtest;

/** 合作模式 1= bidding 2= PD */
@property(nonatomic, readwrite) int32_t ubiddingAdMode;

/** PD合作模式时 下游出价 */
@property(nonatomic, readwrite) uint64_t ubiddingFixedPrice;

@end

#pragma mark - UADXPbAdNetwork

typedef UbiX_GPB_ENUM(UADXPbAdNetwork_FieldNumber) {
  UADXPbAdNetwork_FieldNumber_UbiddingBaseAdNetwork = 1,
  UADXPbAdNetwork_FieldNumber_UbiddingEventsArray = 2,
  UADXPbAdNetwork_FieldNumber_UbiddingUxAdMR = 3,
  UADXPbAdNetwork_FieldNumber_UbiddingMkAdMR = 4,
};

/**
 * UADX 广告源埋点
 **/
UbiX_GPB_FINAL @interface UADXPbAdNetwork : UbiXGPBMessage

/** 公共结构 */
@property(nonatomic, readwrite, strong, null_resettable) UBiddingPbBaseAdNetwork *ubiddingBaseAdNetwork;
/** Test to see if @c ubiddingBaseAdNetwork has been set. */
@property(nonatomic, readwrite) BOOL hasUbiddingBaseAdNetwork;

/** # 事件 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UADXPbEvent*> *ubiddingEventsArray;
/** The number of items in @c ubiddingEventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingEventsArray_Count;

/** UADX 利润率 margin_rate */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingUxAdMR;

/** Merak 利润率 margin_rate */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingMkAdMR;

@end

#pragma mark - UADXPbABTest

typedef UbiX_GPB_ENUM(UADXPbABTest_FieldNumber) {
  UADXPbABTest_FieldNumber_UbiddingAbtestId = 1,
  UADXPbABTest_FieldNumber_UbiddingAbtestGroupId = 2,
};

UbiX_GPB_FINAL @interface UADXPbABTest : UbiXGPBMessage

/** 服务端下发，AB实验ID。（预留字段，默认为空） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAbtestId;

/** 服务端下发，AB实验用户分组ID。（预留字段，默认为空） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAbtestGroupId;

@end

#pragma mark - UBiddingBasePbEvent

typedef UbiX_GPB_ENUM(UBiddingBasePbEvent_FieldNumber) {
  UBiddingBasePbEvent_FieldNumber_UbiddingEventCode = 1,
  UBiddingBasePbEvent_FieldNumber_UbiddingStatusCode = 2,
  UBiddingBasePbEvent_FieldNumber_UbiddingEventGuid = 3,
  UBiddingBasePbEvent_FieldNumber_UbiddingEventTime = 4,
  UBiddingBasePbEvent_FieldNumber_UbiddingDuration = 5,
  UBiddingBasePbEvent_FieldNumber_UbiddingAdnErrorCode = 6,
  UBiddingBasePbEvent_FieldNumber_UbiddingAdnErrorMsg = 7,
  UBiddingBasePbEvent_FieldNumber_UbiddingAdErrorCode = 8,
  UBiddingBasePbEvent_FieldNumber_UbiddingAdErrorMsg = 9,
  UBiddingBasePbEvent_FieldNumber_UbiddingAdFillType = 10,
  UBiddingBasePbEvent_FieldNumber_UbiddingAdnBidCpm = 11,
};

/**
 * 公共事件埋点结构
 **/
UbiX_GPB_FINAL @interface UBiddingBasePbEvent : UbiXGPBMessage

/** 必填，事件码， */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingEventCode;

/** 事件状态码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingStatusCode;

/** 必填，事件发生时生成的唯一id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingEventGuid;

/** 必填，毫秒，时间戳 */
@property(nonatomic, readwrite) int64_t ubiddingEventTime;

/** 请求响应耗时，毫秒 */
@property(nonatomic, readwrite) int64_t ubiddingDuration;

/** adn状态码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnErrorCode;

/** adn错误信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnErrorMsg;

/** 聚合状态码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdErrorCode;

/** 聚合错误信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdErrorMsg;

/** 整体ADN返回类型： 1:全部返回 2:超时，部分ADN返回 3:开发者提前中止 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdFillType;

/** 联盟出价 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnBidCpm;

@end

#pragma mark - UBiddingPbBaseAdRequest

typedef UbiX_GPB_ENUM(UBiddingPbBaseAdRequest_FieldNumber) {
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingAdSlotId = 1,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingAdRequestId = 2,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingAdType = 3,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingAdTrafficGroupId = 4,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingAdTrafficGroupLimitTime = 5,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingAdUseLimitTime = 6,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingUseTrafficGroupCache = 7,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingNetStatusCode = 8,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingSplashStartMode = 9,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingAdBidPrice = 10,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingIsFromCache = 11,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingAdBidfloorCpm = 12,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingServerExtParams = 13,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingCrConfig = 14,
  UBiddingPbBaseAdRequest_FieldNumber_UbiddingIsTrCr = 15,
};

/**
 * 公共广告位埋点结构
 **/
UbiX_GPB_FINAL @interface UBiddingPbBaseAdRequest : UbiXGPBMessage

/** # 公参 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdSlotId;

/** 广告请求id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdRequestId;

/** 广告位类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdType;

/** 策略id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdTrafficGroupId;

/** 策略下发的总超时，毫秒 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdTrafficGroupLimitTime;

/** 用户实际使用的总超时，毫秒 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdUseLimitTime;

/** 是否使用缓存  最终是否使用缓存 1用，2，不用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingUseTrafficGroupCache;

/** 接口请求返回状态码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingNetStatusCode;

/** 开屏的冷热启动。1：热启动；2：冷启动 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingSplashStartMode;

/** 给开发者的出价 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdBidPrice;

/** 1 不来自缓存  2 来自缓存 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingIsFromCache;

/** bidding过滤底价 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdBidfloorCpm;

/** 天权打点透传 本期内容仅AB实验 非必填 服务端扩展参数，字符串第一个字符用于标记压缩方式，0为不压缩，1为zstd压缩；剩下的字符是扩展参数处理之后的标准base64编码字符串；服务端下发后，端上无需关注具体字段。随埋点上报，参数结构在mediation_server_ext_params.proto体现属于内部协议 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingServerExtParams;

/** CTR配置类型：0=未配置(服务端未下发时的默认值)，1=常规(除跳过/关闭按钮外其他区域可点)，2=稳准狠(全区域可点含跳过/关闭)，3=信息流点滑(滑动经过广告区域视为点击)，4=弹窗提示自动跳转(仅信息流映射激励时)，5=静默跳转(无弹窗自动跳转) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingCrConfig;

/** 是否由CTR触发：1=CTR触发 2=用户手动点击(默认) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingIsTrCr;

@end

#pragma mark - UBiddingPbBaseAdNetwork

typedef UbiX_GPB_ENUM(UBiddingPbBaseAdNetwork_FieldNumber) {
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnId = 1,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnSlotId = 2,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdWaterfallIndex = 3,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingBidType = 4,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnVersion = 5,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnBidMoment = 6,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingIsWin = 7,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnRenderMethod = 8,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnAccount = 9,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnAppId = 10,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnSlotInnerId = 11,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnAdapterVersion = 12,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnAdType = 13,
  UBiddingPbBaseAdNetwork_FieldNumber_UbiddingAdnAccountInnerId = 14,
};

/**
 * 公共广告源埋点结构
 **/
UbiX_GPB_FINAL @interface UBiddingPbBaseAdNetwork : UbiXGPBMessage

/** # 策略下发内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnId;

/** 广告源 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnSlotId;

/** 瀑布流层级 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdWaterfallIndex;

/** 竞价类型：1=bidding，2=waterfall */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingBidType;

/** # 初始化 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnVersion;

/** # 渲染 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnBidMoment;

/** # 竞胜 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingIsWin;

/** 广告源的渲染方法：1=信息流模板渲染(FEED_EXPRESS)，2=信息流自渲染(FEED_NATIVE)，3=默认(DEFAULT) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnRenderMethod;

/** 外部广告账户 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnAccount;

/** 广告源应用id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnAppId;

/** 广告源广告位，资产id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnSlotInnerId;

/** 联盟适配器版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnAdapterVersion;

/** 上游代码位广告类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnAdType;

/** 广告账户资产ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingAdnAccountInnerId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
