// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ubidding_material.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/UbiXGPBProtocolBuffers.h>
#else
#import <UbiXDaq/UbiXGPBProtocolBuffers.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UBiddingPbMaterialResponse_UBiddingMaterialInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UbiddingMaterialRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (UbiXGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c UbiXGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
UbiX_GPB_FINAL @interface UbiddingMaterialRoot : UbiXGPBRootObject
@end

#pragma mark - UBiddingPbMaterialRequest

typedef UbiX_GPB_ENUM(UBiddingPbMaterialRequest_FieldNumber) {
  UBiddingPbMaterialRequest_FieldNumber_UbiddingpbAppId = 1,
  UBiddingPbMaterialRequest_FieldNumber_UbiddingpbMaterialsArray = 2,
  UBiddingPbMaterialRequest_FieldNumber_UbiddingpbConfigType = 3,
};

/**
 * 聚合素材实时接口请求格式
 **/
UbiX_GPB_FINAL @interface UBiddingPbMaterialRequest : UbiXGPBMessage

/** 聚合应用id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbAppId;

/** 素材url的md5值 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *ubiddingpbMaterialsArray;
/** The number of items in @c ubiddingpbMaterialsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbMaterialsArray_Count;

/** 1:Saas， 2:UADX */
@property(nonatomic, readwrite) int32_t ubiddingpbConfigType;

@end

#pragma mark - UBiddingPbMaterialResponse

typedef UbiX_GPB_ENUM(UBiddingPbMaterialResponse_FieldNumber) {
  UBiddingPbMaterialResponse_FieldNumber_UbiddingpbMaterialInfoArray = 1,
  UBiddingPbMaterialResponse_FieldNumber_UbiddingpbStatusCode = 2,
};

/**
 * 聚合素材实时接口返回格式
 **/
UbiX_GPB_FINAL @interface UBiddingPbMaterialResponse : UbiXGPBMessage

/** 素材返回对象。 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UBiddingPbMaterialResponse_UBiddingMaterialInfo*> *ubiddingpbMaterialInfoArray;
/** The number of items in @c ubiddingpbMaterialInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ubiddingpbMaterialInfoArray_Count;

/** 0-正常 非0对应错误码 */
@property(nonatomic, readwrite) int32_t ubiddingpbStatusCode;

@end

#pragma mark - UBiddingPbMaterialResponse_UBiddingMaterialInfo

typedef UbiX_GPB_ENUM(UBiddingPbMaterialResponse_UBiddingMaterialInfo_FieldNumber) {
  UBiddingPbMaterialResponse_UBiddingMaterialInfo_FieldNumber_UbiddingpbStatus = 1,
  UBiddingPbMaterialResponse_UBiddingMaterialInfo_FieldNumber_UbiddingpbMaterialId = 2,
  UBiddingPbMaterialResponse_UBiddingMaterialInfo_FieldNumber_UbiddingpbMaterialRuleIds = 3,
};

UbiX_GPB_FINAL @interface UBiddingPbMaterialResponse_UBiddingMaterialInfo : UbiXGPBMessage

/** 1：在黑名单中，2:不在黑名单中 */
@property(nonatomic, readwrite) int32_t ubiddingpbStatus;

/** 黑名单素材id。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbMaterialId;

/** 黑名单素材规则 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ubiddingpbMaterialRuleIds;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
